name: Setup EC2 Linux

description: Setup EC2 Linux

inputs:
  GITHUB_TOKEN:
    required: true

runs:
  using: composite
  steps:
    - name: Checkout PyTorch
      uses: pytorch/pytorch/.github/actions/checkout-pytorch@master
    - name: Setup Linux
      uses: ./.github/actions/setup-linux
    - name: Chown workspace
        uses: ./.github/actions/chown-workspace
    - name: Clean workspace
      run: |
        rm -rf "${GITHUB_WORKSPACE}"
        mkdir "${GITHUB_WORKSPACE}"
    - name: "Enable SSH (Click me for login details)"
      uses: ./.github/actions/setup-ssh/action.yml
      with:
        github-secret: ${{ secrets.GITHUB_TOKEN }}
