name: Teardown Linux

description: Stuff that should always run at the end of a linux job

inputs:
  skip-wait-ssh:
    description: If set, don't wait for ssh to drain before tearing down
    required: false
    default: ""
  pytorch-repo-directory:
    description: Path to root of pytorch repo
    default: "."

runs:
  using: composite
  steps:
    - name: Hold runner for 2 hours or until ssh sessions have drained
      # TODO working-directory: !{{ pytorch_directory }}
      # Always hold for active ssh sessions
      shell: bash
      working-directory: ${{ inputs.pytorch-repo-directory }}
      if: inputs.skip-wait-ssh == ''
      run: .github/scripts/wait_for_ssh_to_drain.sh

    - name: Chown workspace
      uses: ./.github/actions/chown-workspace

    - name: Kill containers, clean up images
      shell: bash
      run: |
        # ignore expansion of "docker ps -q" since it could be empty
        # shellcheck disable=SC2046
        docker stop $(docker ps -q) || true
        # Prune all of the docker images
        docker system prune -af
